"""Add fields for users to add optional data to meals table

Revision ID: 08269e1197d0
Revises: e0b2cdd41759
Create Date: 2021-07-06 14:15:25.066244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08269e1197d0'
down_revision = 'e0b2cdd41759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('meal_title', sa.String(length=100), nullable=True))
    op.add_column('meals', sa.Column('meal_notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'meal_notes')
    op.drop_column('meals', 'meal_title')
    # ### end Alembic commands ###
