"""update users-followers relationship

Revision ID: 87d359ed4e72
Revises: a98f79566cc1
Create Date: 2021-07-10 17:24:34.809785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d359ed4e72'
down_revision = 'a98f79566cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    op.drop_table('follows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_following_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_being_followed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_being_followed_id'], ['users.id'], name='follows_user_being_followed_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_following_id'], ['users.id'], name='follows_user_following_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='follows_pkey'),
    sa.UniqueConstraint('user_following_id', 'user_being_followed_id', name='follows_user_following_id_user_being_followed_id_key')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###
