"""update meals table

Revision ID: c91e22c8d6e0
Revises: 2f0218d2346b
Create Date: 2021-07-06 12:22:24.146136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91e22c8d6e0'
down_revision = '2f0218d2346b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('recipe_id', sa.Integer(), nullable=False))
    op.add_column('meals', sa.Column('recipe_title', sa.String(), nullable=False))
    op.add_column('meals', sa.Column('recipe_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'recipe_url')
    op.drop_column('meals', 'recipe_title')
    op.drop_column('meals', 'recipe_id')
    # ### end Alembic commands ###
