"""update meals table

Revision ID: e0b2cdd41759
Revises: c91e22c8d6e0
Create Date: 2021-07-06 12:45:34.670046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b2cdd41759'
down_revision = 'c91e22c8d6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('recipe_title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'recipe_title')
    # ### end Alembic commands ###
