"""Add recipe title to recipe_boxes table

Revision ID: e94231ebff2e
Revises: 87d359ed4e72
Create Date: 2021-07-12 09:11:25.966116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94231ebff2e'
down_revision = '87d359ed4e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_boxes', sa.Column('recipe_title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_boxes', 'recipe_title')
    # ### end Alembic commands ###
