"""Add UniqueConstraint to recipe_boxes

Revision ID: ea8b88183414
Revises: 40a2a95ff239
Create Date: 2021-06-29 20:09:54.553234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8b88183414'
down_revision = '40a2a95ff239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'recipe_boxes', ['recipe_url', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_boxes', type_='unique')
    # ### end Alembic commands ###
